# Use Node.js official image as the base
FROM node:latest

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Expose the port that the app will run on
EXPOSE 3001

# Start the NestJS application
CMD ["npm", "run", "start:prod"]
